language: node_js
node_js:
  - stable

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE USER test_user WITH PASSWORD 'test';" -U postgres
  - psql -U postgres test_db -c 'CREATE EXTENSION "uuid-ossp";'

script:
  - echo "Integration test starts....."
  - npm run ci-test

after_script:
  - npm run coverage