language: node_js
node_js:
  - stable

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE auth_test;" -U postgres
  - psql -c "CREATE USER test_user WITH PASSWORD 'test';" -U postgres
  - psql -U postgres auth_test -c 'CREATE EXTENSION "uuid-ossp";'

script:
  - echo "Integration test starts....."
  - npm run test

after_script:
  - npm run coverage